In [3]:
before="/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_fixed/af3_sp2_output/1a4y_sp2_rand0.2/gather/cov_tensor.pt"
after="/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_fixed/af3_sp2_output/1a4y_sp2_rand0.2/gather/af_cov_tensor.pt"
import torch
before_tensor=torch.load(before)
after_tensor=torch.load(after)

print(before_tensor)
print(after_tensor)


corr="/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_fixed/af3_sp2_output/1a4y_sp2_rand0.2/gather/af_corr_tensor.pt"
corr_tensor=torch.load(corr)
print(corr_tensor)


tensor([[ 2.2266e+00,  2.6064e-01,  9.5200e-01,  ..., -5.7512e-02,
          3.1756e-01, -2.6468e-01],
        [ 2.6064e-01,  5.1376e-02,  1.2813e-01,  ...,  1.3758e-02,
          4.5396e-02, -3.5038e-02],
        [ 9.5200e-01,  1.2813e-01,  4.2456e-01,  ..., -6.3422e-03,
          1.4282e-01, -1.0508e-01],
        ...,
        [-5.7512e-02,  1.3758e-02, -6.3422e-03,  ...,  2.4241e-02,
          1.7148e-03,  6.1859e-03],
        [ 3.1756e-01,  4.5396e-02,  1.4282e-01,  ...,  1.7148e-03,
          5.0066e-02, -3.9638e-02],
        [-2.6468e-01, -3.5038e-02, -1.0508e-01,  ...,  6.1859e-03,
         -3.9638e-02,  6.4651e-02]])
tensor([[ 2.1963,  1.4521,  0.8626,  ..., -0.2018, -0.2895, -0.2064],
        [ 1.4521,  0.9773,  0.5743,  ..., -0.1199, -0.1622, -0.1384],
        [ 0.8626,  0.5743,  0.3461,  ..., -0.0658, -0.0997, -0.0789],
        ...,
        [-0.2018, -0.1199, -0.0658,  ...,  0.0459,  0.0613,  0.0217],
        [-0.2895, -0.1622, -0.0997,  ...,  0.0613,  0.1003,  0.0281],
     

In [4]:
corr_tensor[0]

tensor([ 1.0000,  0.9911,  0.9895,  0.8875,  0.9081,  0.8564,  0.7716,  0.8021,
         0.7750,  0.7329,  0.7052,  0.5171,  0.1175,  0.3382,  0.3886,  0.1126,
         0.5913,  0.6087,  0.4759,  0.6185,  0.6560,  0.6086,  0.6953,  0.8183,
         0.8149,  0.7826,  0.7900,  0.8146,  0.8112,  0.8117,  0.7919,  0.8152,
         0.8578,  0.6207,  0.5446,  0.4339,  0.1915, -0.1652, -0.2063,  0.0348,
        -0.0428, -0.1179, -0.4235, -0.6255, -0.0492,  0.2228,  0.3687,  0.4753,
         0.5095,  0.6426,  0.7639,  0.4944,  0.5430,  0.7419,  0.8428,  0.8303,
         0.8014,  0.7816,  0.8965,  0.7033,  0.7682,  0.0793,  0.7333,  0.4505,
         0.1487, -0.2331, -0.6444, -0.4723, -0.1758, -0.1293, -0.9363, -0.9606,
         0.3901, -0.3986,  0.0037,  0.4515,  0.4660,  0.3051,  0.6329,  0.1835,
         0.1493,  0.7316,  0.6965,  0.6882,  0.7074,  0.5544,  0.4444,  0.4731,
         0.3981,  0.4867, -0.1535, -0.1418,  0.3212,  0.2905, -0.1648,  0.4067,
         0.2718,  0.7008,  0.6180,  0.66

In [5]:
import torch

corr_path = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_mutated/af3_sp2_output/1a4y_da435a_sp2_rand0.2/gather/corr_tensor.pt"
rand_path = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_mutated/af3_sp2_output/1a4y_da435a_sp2_rand0.2/gather/rand.pt"

corr_tensor = torch.load(corr_path)
rand_tensor = torch.load(rand_path)

print("Correlation tensor:")
print(corr_tensor)
print("Random tensor:")
print(rand_tensor)


Correlation tensor:
tensor([[ 1.0000,  0.9935,  0.9865,  ...,  0.4230, -0.8854,  0.0830],
        [ 0.9935,  1.0000,  0.9643,  ...,  0.5107, -0.8851,  0.1865],
        [ 0.9865,  0.9643,  1.0000,  ...,  0.2719, -0.8916, -0.0793],
        ...,
        [ 0.4230,  0.5107,  0.2719,  ...,  1.0000, -0.2389,  0.9167],
        [-0.8854, -0.8851, -0.8916,  ..., -0.2389,  1.0000, -0.0159],
        [ 0.0830,  0.1865, -0.0793,  ...,  0.9167, -0.0159,  1.0000]])
Random tensor:
tensor([[ 1.0000,  0.5101,  0.3765,  ..., -0.8181,  0.0972,  0.2233],
        [ 0.5101,  1.0000,  0.0619,  ..., -0.6699, -0.4251,  0.1458],
        [ 0.3765,  0.0619,  1.0000,  ..., -0.2784,  0.4993, -0.0314],
        ...,
        [-0.8181, -0.6699, -0.2784,  ...,  1.0000, -0.2751,  0.6769],
        [ 0.0972, -0.4251,  0.4993,  ..., -0.2751,  1.0000,  0.0077],
        [ 0.2233,  0.1458, -0.0314,  ...,  0.6769,  0.0077,  1.0000]])


In [1]:
import torch

corr_path = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_mutated/af3_sp2_output/1a4y_da435a_sp2_rand0.2/gather/corr_tensor.pt"
rand_path = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_mutated/af3_sp2_output/1a4y_da435a_sp2_rand0.2/gather/rand.pt"
repr_path = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_mutated/af3_sp2_output/1a4y_da435a_sp2_rand0.2/gather/repr_within_pt_tensor.pt"
corr_tensor = torch.load(corr_path)
rand_tensor = torch.load(rand_path)
repr_tensor = torch.load(repr_path)
print("Correlation tensor:")
print(corr_tensor)
print("Random tensor:")
print(rand_tensor)
print("repr tensor:")
print(repr_tensor)
#shape
print(repr_tensor.shape)
print(corr_tensor.shape)
print(rand_tensor.shape)


Correlation tensor:
tensor([[ 1.0000,  0.9935,  0.9865,  ...,  0.4230, -0.8854,  0.0830],
        [ 0.9935,  1.0000,  0.9643,  ...,  0.5107, -0.8851,  0.1865],
        [ 0.9865,  0.9643,  1.0000,  ...,  0.2719, -0.8916, -0.0793],
        ...,
        [ 0.4230,  0.5107,  0.2719,  ...,  1.0000, -0.2389,  0.9167],
        [-0.8854, -0.8851, -0.8916,  ..., -0.2389,  1.0000, -0.0159],
        [ 0.0830,  0.1865, -0.0793,  ...,  0.9167, -0.0159,  1.0000]])
Random tensor:
tensor([[ 1.0000,  0.5101,  0.3765,  ..., -0.8181,  0.0972,  0.2233],
        [ 0.5101,  1.0000,  0.0619,  ..., -0.6699, -0.4251,  0.1458],
        [ 0.3765,  0.0619,  1.0000,  ..., -0.2784,  0.4993, -0.0314],
        ...,
        [-0.8181, -0.6699, -0.2784,  ...,  1.0000, -0.2751,  0.6769],
        [ 0.0972, -0.4251,  0.4993,  ..., -0.2751,  1.0000,  0.0077],
        [ 0.2233,  0.1458, -0.0314,  ...,  0.6769,  0.0077,  1.0000]])
repr tensor:
tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00

In [3]:
cov_tensor

tensor([[ 1.1694,  0.6656,  0.5148,  ...,  0.2515, -0.3529,  0.2191],
        [ 0.6656,  0.3838,  0.2883,  ...,  0.1740, -0.2021,  0.2823],
        [ 0.5148,  0.2883,  0.2329,  ...,  0.0721, -0.1586, -0.0935],
        ...,
        [ 0.2515,  0.1740,  0.0721,  ...,  0.3024, -0.0484,  1.2313],
        [-0.3529, -0.2021, -0.1586,  ..., -0.0484,  0.1359, -0.0143],
        [ 0.2191,  0.2823, -0.0935,  ...,  1.2313, -0.0143,  5.9671]])

In [6]:
#取出cov_tensor对角线上元素 从大到小排序 提供index
import torch

pth="/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_mutated/af3_sp2_output/1a4y_da435a_sp2_rand0.2/gather/cov_tensor.pt"
cov_tensor = torch.load(pth)
# 取出cov_tensor对角线上元素
diag_elements = torch.diag(cov_tensor)

# 从大到小排序
sorted_indices = torch.argsort(diag_elements, descending=True)

# 获取排序后的对角线元素
sorted_diag_elements = diag_elements[sorted_indices]
sorted_indices

    

tensor([582,   0, 517, 367, 518,   1, 580,   2, 547, 497, 550, 552, 496, 581,
        546, 458, 545, 554, 549, 551, 459, 548, 553, 498, 457, 456, 421, 454,
        527, 452, 543, 451, 526, 455, 519, 422, 579,   3, 544, 409, 556, 481,
        557, 309, 538,  82, 443, 460, 423, 440, 482, 555, 430, 444,  81, 479,
        541, 542, 439, 495, 486,  98, 537, 448,  54, 450, 429, 447, 525, 483,
        410,  27, 442, 449, 446, 453, 512, 308, 431,  52, 578, 445,  55,  62,
        432, 487,  53, 438, 441,  84, 516, 382, 484, 428, 504, 539, 524, 424,
        485,   6, 126, 505, 411, 216, 437, 536, 493,   8,  83, 480, 503,  80,
        420, 499, 366, 513,  79, 374, 413, 506,  48,  28, 462, 419, 540, 383,
        307,  16, 425,  19, 417,   7, 507,  40, 463, 466,  31, 109, 465, 514,
        577, 509, 105, 558, 412, 535,  15, 414, 405, 472,  56, 375, 473, 427,
        470,  20, 510, 500,  29, 515, 110,  49,   9, 224, 567, 426, 127, 310,
         26, 253, 464, 108, 492, 461,  47, 521, 561,  24, 381,  

tensor([582,   0, 517, 367, 518,   1, 580,   2, 547, 497, 550, 552, 496, 581,
        546, 458, 545, 554, 549, 551, 459, 548, 553, 498, 457, 456, 421, 454,
        527, 452, 543, 451, 526, 455, 519, 422, 579,   3, 544, 409, 556, 481,
        557, 309, 538,  82, 443, 460, 423, 440, 482, 555, 430, 444,  81, 479,
        541, 542, 439, 495, 486,  98, 537, 448,  54, 450, 429, 447, 525, 483,
        410,  27, 442, 449, 446, 453, 512, 308, 431,  52, 578, 445,  55,  62,
        432, 487,  53, 438, 441,  84, 516, 382, 484, 428, 504, 539, 524, 424,
        485,   6, 126, 505, 411, 216, 437, 536, 493,   8,  83, 480, 503,  80,
        420, 499, 366, 513,  79, 374, 413, 506,  48,  28, 462, 419, 540, 383,
        307,  16, 425,  19, 417,   7, 507,  40, 463, 466,  31, 109, 465, 514,
        577, 509, 105, 558, 412, 535,  15, 414, 405, 472,  56, 375, 473, 427,
        470,  20, 510, 500,  29, 515, 110,  49,   9, 224, 567, 426, 127, 310,
         26, 253, 464, 108, 492, 461,  47, 521, 561,  24, 381,  

In [1]:
import torch
pth = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_fixed/af3_sp2_output/3r9a_sp2_rand0.2/gather/repr_within_pt_tensor.pt"
tensor = torch.load(pth)
print(tensor)

tensor([[[0.0000e+00, 0.0000e+00, 1.5625e-02,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [3.8607e+00, 3.8601e+00, 3.8494e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [5.5739e+00, 5.5504e+00, 5.6122e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         ...,
         [5.1610e+01, 5.4056e+01, 5.1545e+01,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [5.3228e+01, 5.5828e+01, 5.3410e+01,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [5.4365e+01, 5.9138e+01, 5.2585e+01,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[3.8607e+00, 3.8601e+00, 3.8494e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [3.8373e+00, 3.8325e+00, 3.8281e+00,  ..., 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         ...,
         [5.3845e+01, 5.6333e+01, 5.3830e+01,  ..., 0.0000e+00,
          0.000

In [4]:
print(tensor[0,0])
print(tensor[1, 1])
print(tensor[2, 2])

tensor([0.0000, 0.0000, 0.0156, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0156,
        0.0031, 0.0070, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [6]:
import torch
pth = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_fixed/af3_sp2_output/3r9a_sp2_rand0.2/gather/rand_repr_within_pt_tensor.pt"
tensor = torch.load(pth)
# print(tensor)
print(tensor[0, 0])
print(tensor[1, 1])
print(tensor[2, 2])

tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [3]:
import torch
import os
# Load the random representation tensor
_path = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_mutated/af3_sp2_output/1a22_pa48a_sp2_rand0.2/gather"
sp_rand_tensor = torch.load(os.path.join(_path,"sp_rand_roi_tensor.pt"))
sp_rand_indices=torch.load(os.path.join(_path,"sp_rand_mask_roi.pt"))

rand_tensor = torch.load(os.path.join(_path, "rand_roi_tensor.pt"))
rand_indices=torch.load(os.path.join(_path,"rand_mask_roi.pt"))

tensor = torch.load(os.path.join(_path, "roi_tensor.pt"))
indices=torch.load(os.path.join(_path,"mask_roi.pt"))

print("Original indices:")
print(torch.where(indices==1))
print("\nRandom indices:")
print(torch.where(rand_indices==1))
print("\nSP Random indices:")
print(torch.where(sp_rand_indices==1))
print(tensor.shape)
print(rand_tensor.shape)
print(sp_rand_tensor.shape)
print(tensor[0,1])
print(rand_tensor[0,1])
print(sp_rand_tensor[0,1])

Original indices:
(tensor([ 17,  18,  20,  21,  22,  23,  24,  25,  28,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67, 152, 153, 155,
        156, 157, 159, 160, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
        175, 176, 177, 178, 179, 190, 191, 192, 207, 208, 209, 210, 211, 212,
        213, 214, 215, 216, 217, 236, 237, 238, 239, 240, 241, 242, 243, 244,
        245, 246, 247, 258, 259, 260, 261, 262, 264, 265, 292, 293, 298, 299,
        300, 301, 302, 303, 304, 305, 306, 327, 328, 329, 330, 351, 352, 353,
        354]),)

Random indices:
(tensor([ 17,  18,  19,  20,  21,  22,  23,  24,  25,  28,  37,  38,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  50,  51,  52,  55,  56,  59,  60,
         61,  62,  63,  64,  65,  66,  67, 153, 155, 156, 157, 158, 159, 160,
        162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 175, 176, 177, 178,
        179