In [3]:
before="/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_fixed/af3_sp2_output/1a4y_sp2_rand0.2/gather/cov_tensor.pt"
after="/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_fixed/af3_sp2_output/1a4y_sp2_rand0.2/gather/af_cov_tensor.pt"
import torch
before_tensor=torch.load(before)
after_tensor=torch.load(after)

print(before_tensor)
print(after_tensor)


corr="/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_fixed/af3_sp2_output/1a4y_sp2_rand0.2/gather/af_corr_tensor.pt"
corr_tensor=torch.load(corr)
print(corr_tensor)


tensor([[ 2.2266e+00,  2.6064e-01,  9.5200e-01,  ..., -5.7512e-02,
          3.1756e-01, -2.6468e-01],
        [ 2.6064e-01,  5.1376e-02,  1.2813e-01,  ...,  1.3758e-02,
          4.5396e-02, -3.5038e-02],
        [ 9.5200e-01,  1.2813e-01,  4.2456e-01,  ..., -6.3422e-03,
          1.4282e-01, -1.0508e-01],
        ...,
        [-5.7512e-02,  1.3758e-02, -6.3422e-03,  ...,  2.4241e-02,
          1.7148e-03,  6.1859e-03],
        [ 3.1756e-01,  4.5396e-02,  1.4282e-01,  ...,  1.7148e-03,
          5.0066e-02, -3.9638e-02],
        [-2.6468e-01, -3.5038e-02, -1.0508e-01,  ...,  6.1859e-03,
         -3.9638e-02,  6.4651e-02]])
tensor([[ 2.1963,  1.4521,  0.8626,  ..., -0.2018, -0.2895, -0.2064],
        [ 1.4521,  0.9773,  0.5743,  ..., -0.1199, -0.1622, -0.1384],
        [ 0.8626,  0.5743,  0.3461,  ..., -0.0658, -0.0997, -0.0789],
        ...,
        [-0.2018, -0.1199, -0.0658,  ...,  0.0459,  0.0613,  0.0217],
        [-0.2895, -0.1622, -0.0997,  ...,  0.0613,  0.1003,  0.0281],
     

In [4]:
corr_tensor[0]

tensor([ 1.0000,  0.9911,  0.9895,  0.8875,  0.9081,  0.8564,  0.7716,  0.8021,
         0.7750,  0.7329,  0.7052,  0.5171,  0.1175,  0.3382,  0.3886,  0.1126,
         0.5913,  0.6087,  0.4759,  0.6185,  0.6560,  0.6086,  0.6953,  0.8183,
         0.8149,  0.7826,  0.7900,  0.8146,  0.8112,  0.8117,  0.7919,  0.8152,
         0.8578,  0.6207,  0.5446,  0.4339,  0.1915, -0.1652, -0.2063,  0.0348,
        -0.0428, -0.1179, -0.4235, -0.6255, -0.0492,  0.2228,  0.3687,  0.4753,
         0.5095,  0.6426,  0.7639,  0.4944,  0.5430,  0.7419,  0.8428,  0.8303,
         0.8014,  0.7816,  0.8965,  0.7033,  0.7682,  0.0793,  0.7333,  0.4505,
         0.1487, -0.2331, -0.6444, -0.4723, -0.1758, -0.1293, -0.9363, -0.9606,
         0.3901, -0.3986,  0.0037,  0.4515,  0.4660,  0.3051,  0.6329,  0.1835,
         0.1493,  0.7316,  0.6965,  0.6882,  0.7074,  0.5544,  0.4444,  0.4731,
         0.3981,  0.4867, -0.1535, -0.1418,  0.3212,  0.2905, -0.1648,  0.4067,
         0.2718,  0.7008,  0.6180,  0.66

In [5]:
import torch

corr_path = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_mutated/af3_sp2_output/1a4y_da435a_sp2_rand0.2/gather/corr_tensor.pt"
rand_path = "/home/lmh/projects_dir/Antibody_Mutation/data/SKEMPIv2/PDBs_mutated/af3_sp2_output/1a4y_da435a_sp2_rand0.2/gather/rand.pt"

corr_tensor = torch.load(corr_path)
rand_tensor = torch.load(rand_path)

print("Correlation tensor:")
print(corr_tensor)
print("Random tensor:")
print(rand_tensor)


Correlation tensor:
tensor([[ 1.0000,  0.9935,  0.9865,  ...,  0.4230, -0.8854,  0.0830],
        [ 0.9935,  1.0000,  0.9643,  ...,  0.5107, -0.8851,  0.1865],
        [ 0.9865,  0.9643,  1.0000,  ...,  0.2719, -0.8916, -0.0793],
        ...,
        [ 0.4230,  0.5107,  0.2719,  ...,  1.0000, -0.2389,  0.9167],
        [-0.8854, -0.8851, -0.8916,  ..., -0.2389,  1.0000, -0.0159],
        [ 0.0830,  0.1865, -0.0793,  ...,  0.9167, -0.0159,  1.0000]])
Random tensor:
tensor([[ 1.0000,  0.5101,  0.3765,  ..., -0.8181,  0.0972,  0.2233],
        [ 0.5101,  1.0000,  0.0619,  ..., -0.6699, -0.4251,  0.1458],
        [ 0.3765,  0.0619,  1.0000,  ..., -0.2784,  0.4993, -0.0314],
        ...,
        [-0.8181, -0.6699, -0.2784,  ...,  1.0000, -0.2751,  0.6769],
        [ 0.0972, -0.4251,  0.4993,  ..., -0.2751,  1.0000,  0.0077],
        [ 0.2233,  0.1458, -0.0314,  ...,  0.6769,  0.0077,  1.0000]])
