In [2]:
from torch import tensor
from torchmetrics.classification import MulticlassAccuracy
target = tensor([2, 1, 0, 0])
preds = tensor([2, 1, 0, 1])
metric = MulticlassAccuracy(num_classes=3,average='micro')
metric(preds, target)

tensor(0.7500)

In [3]:
from torch import tensor
from torchmetrics.classification import MulticlassAccuracy
target = tensor([2, 1, 0, 0])
preds = tensor([2, 1, 0, 1])
metric = MulticlassAccuracy(num_classes=3,average='macro')
metric(preds, target)

tensor(0.8333)

In [6]:
from torch import tensor
from torchmetrics.classification import MulticlassAccuracy
target = tensor([[2], [1], [0], [0]])
preds = tensor([[2], [1], [0], [1]])
metric = MulticlassAccuracy(num_classes=3,average='macro',multidim_average='samplewise')
metric(preds, target)

tensor([1., 1., 1., 0.])

In [2]:
from torchmetrics.classification import BinaryAccuracy
from torch import tensor
target = tensor([[[0, 1], [1, 0], [0, 1]], [[1, 1], [0, 0], [1, 0]]])
preds = tensor([[[0.59, 0.91], [0.91, 0.99], [0.63, 0.04]],
                [[0.38, 0.04], [0.86, 0.780], [0.45, 0.37]]])
metric = BinaryAccuracy(multidim_average='samplewise')
metric(preds, target)


tensor([0.3333, 0.1667])

In [4]:
from torchmetrics.classification import BinaryAccuracy
import torch

# 假设有 3 个样本，2 个类别
target = torch.tensor([[0, 1,1], [1, 0,1], [0, 1,1]])  # 标签
preds = torch.tensor([[0.59, 0.91,0.91], [0.91, 0.2,0.91], [0.63, 0.04,0.91]])  # 预测概率

# 初始化 BinaryAccuracy 指标
metric = BinaryAccuracy(multidim_average='samplewise')  # 按样本维度计算平均值
accuracy = metric(preds, target)

print(accuracy)

tensor([0.6667, 1.0000, 0.3333])
